---
- name: non-free-contrib-repo
  hosts: all
  become: true
  roles:
    - role: claranet.apt
      vars:
        apt_upgrade: true
        apt_packages:
          - name: apache2
        apt_repositories:
          # contrib repo
          - types: deb
            urls: "http://deb.debian.org/{{ ansible_distribution | lower }}"
            suites: "{{ ansible_distribution_release }}"
            components: "contrib"
          # non-free repo
          - types: deb
            urls: "http://deb.debian.org/{{ ansible_distribution | lower }}"
            suites: "{{ ansible_distribution_release }}"
            components: "non-free"
