---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian7
    image: debian:7
  - name: debian8
    image: debian:8
  - name: debian9
    image: debian:9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: non-free_contrib_repo
verifier:
  name: testinfra
  lint:
    name: flake8
