---
- name: non-free-contrib-repo
  remote_user: ansible
  hosts: all
  roles:
    - role: ansible-role-apt
  vars:
    apt_upgrade: true
    apt_packages:
      - name: java-package
      - name: rar

    apt_repositories:
      # contrib repo
      - repo: deb http://deb.debian.org/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} contrib
      # non-free repo
      - repo: deb http://deb.debian.org/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} non-free
      # dotdeb repo
      - repo: deb http://packages.dotdeb.org {{ ansible_distribution_release }} all
    apt_keys:
      - url: https://www.dotdeb.org/dotdeb.gpg
