---
image: python:2.7
pipelines:
  default:
    - step:
        script:
          - ln -s $PWD ../$BITBUCKET_REPO_SLUG && cd ../$BITBUCKET_REPO_SLUG
          - pip install tox
          - tox
        services:
          - docker
