---
- name: "Set facts"
  ansible.builtin.set_fact:
    _apt_extract_urls: "{{ item.urls | join('') if item.urls is not string else item.urls }}"
    _apt_extract_suites: "{{ item.suites | join('') if item.suites is not string else item.suites }}"

- name: Construct path to store apt keys
  ansible.builtin.set_fact:
    _apt_construct_key_path_from_content: "{{ (_apt_extract_urls + _apt_extract_suites) | regex_replace('/| ', '') | regex_replace(':', '-') }}"
    _apt_construct_key_path_from_url: "{{ item.key | urlsplit('path') | regex_replace('/|_', '') | regex_replace(':', '-') }}"

- name: Set fact for final apt key fact
  ansible.builtin.set_fact:
    _apt_key_path: "{{ (item.key is url) | ternary(_apt_construct_key_path_from_url, _apt_construct_key_path_from_content) }}"

- name: "Adding repositories files for new distributions"
  ansible.builtin.template:
    src: "etc/apt/sources.list.d/99ansible.sources"
    dest: "/etc/apt/sources.list.d/99ansible.sources"
    mode: '0755'

- name: "Download apt keys"  # noqa: var-spacing
  ansible.builtin.get_url:
    url: "{{ item.key }}"
    dest: "/usr/share/keyrings/{{ _apt_key_path }}"
    mode: "0664"
    validate_certs: "{{ item.key.validate_certs | default(false) }}"
  when:
    - item.key is url

- name: "Save content of key to a file"
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/usr/share/keyrings/{{ _apt_key_path }}"
    mode: '0664'
  when:
    - item.key is not url

- name: "Generate gpg keys"  # noqa: var-spacing
  ansible.builtin.command:
    cmd: "gpg --dearmor /usr/share/keyrings/{{ _apt_key_path }}"
    creates: "/usr/share/keyrings/{{ _apt_key_path }}.gpg"
    chdir: "/usr/share/keyrings"
  register: _apt_generate_gpt_keys
  changed_when: _apt_generate_gpt_keys.rc != 0
