---
- name: "Installing required packages"
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"
  loop: "{{ _apt_required_packages }}"

- name: "Ensure directory structure exists"
  ansible.builtin.file:
    path: "/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"  # noqa: deprecated-bare-vars
  when: item.state == "directory"

- name: "Ensure files are populated from templates"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/{{ item.path }}"
    mode: '0444'
  with_community.general.filetree: "../templates"  # noqa: deprecated-bare-vars
  when:
    - item.state == "file"
    - item.path != "etc/apt/sources.list.d/99ansible.sources"

- name: "Manage apt repositories"
  ansible.builtin.include_tasks: "apt_repositories.yml"
  when:
    - not apt_keys
    - apt_repositories
  loop: "{{ apt_repositories }}"
  loop_control:
    label: "{{ item.urls | join(' ') if item.urls is not string else item.urls }}"

- name: "Adding ppa repositories"
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ item.codename | default(omit) }}"
    update_cache: true
  loop: "{{ apt_ppas }}"
  loop_control:
    label: "{{ item.repo }}"
  when: item.repo is defined

- name: "Upgrading system"
  become: true
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade }}"
    update_cache: true
    autoremove: "{{ apt_autoremove }}"
  when: apt_upgrade

- name: "Installing packages"
  become: true
  ansible.builtin.apt:
    name: "{{ item.name | default(omit) }}"
    deb: "{{ item.deb | default(omit) }}"
    state: present
    autoremove: "{{ apt_autoremove }}"
    force: "{{ apt_force }}"
    dpkg_options: "{{ apt_dpkg_options | default(omit) }}"
    install_recommends: "{{ apt_install_recommends }}"
    default_release: "{{ apt_default_release | default(omit) }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  loop: "{{ apt_packages }}"

- name: "Package unattended-upgrades"
  ansible.builtin.apt:
    name: unattended-upgrades
    state: >-
      {%- if apt_config_unattended_upgrades_package_state == 'auto' -%}
      {{- (_apt_config_.APT.Periodic['Unattended-Upgrade'] == 1) | ternary('present', 'absent') -}}
      {%- else -%}
      {{- apt_config_unattended_upgrades_package_state -}}
      {%- endif -%}
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: "Package apt-listchanges"
  ansible.builtin.apt:
    name: apt-listchanges
    state: >-
      {%- if apt_config_listchanges_package_state == 'auto' -%}
      {{- (apt_config_listchanges_mail is not none) | ternary('present', 'absent') -}}
      {%- else -%}
      {{- apt_config_listchanges_package_state -}}
      {%- endif -%}
    cache_valid_time: "{{ apt_cache_valid_time }}"
