---
- name: Installing required packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - aptitude
    - python-apt
    - python-pycurl
  become: true

- name: Adding apt signing key
  apt_key:
    id: "{{ item.id | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    data: "{{ item.data | default(omit) }}"
    keyring: "{{ item.keyring | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
    state: present
  with_items: "{{ apt_keys }}"
  become: true

- name: Adding repositories
  apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ item.codename | default (omit) }}"
    update_cache: true
  with_items: "{{ apt_repositories }}"
  when: item.repo is defined
  become: true

- name: Upgrading system
  apt:
    upgrade: "{{ apt_upgrade }}"
    update_cache: true
    autoremove: "{{ apt_autoremove }}"
  when: apt_upgrade
  become: true

- name: Installing packages
  apt:
    name: "{{ item.name | default(omit) }}"
    deb: "{{ item.deb | default(omit) }}"
    state: present
    autoremove: "{{ apt_autoremove }}"
    force: "{{ apt_force }}"
    dpkg_options: "{{ apt_dpkg_options | default(omit) }}"
    install_recommends: "{{ apt_install_recommends }}"
    default_release: "{{ apt_default_release | default(omit) }}"
    update_cache: true
  with_items: "{{ apt_packages }}"
  become: true
