---

- name: Ensure directory structure exists
  ansible.builtin.file:
    path: "/{{ item.path }}"
    state: directory
    mode: '0755'
  with_filetree: "{{ ['../templates'] }}"  # noqa: schema
  when: item.state == "directory"

- name: Ensure files are populated from templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/{{ item.path }}"
    mode: '0444'
  with_filetree: "{{ ['../templates'] }}"  # noqa: schema
  when: item.state == "file"

- name: Installing required packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{ _apt_required_packages }}"
  become: true

- name: Adding apt signing key
  ansible.builtin.apt_key:
    id: "{{ item.id | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    data: "{{ item.data | default(omit) }}"
    keyring: "{{ item.keyring | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
    state: present
  loop: "{{ apt_keys }}"
  become: true

- name: Adding repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ item.codename | default (omit) }}"
    update_cache: true
  loop: "{{ apt_repositories }}"
  when: item.repo is defined
  become: true

- name: Upgrading system
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade }}"
    update_cache: true
    autoremove: "{{ apt_autoremove }}"
  when: apt_upgrade
  become: true

- name: Installing packages
  ansible.builtin.apt:
    name: "{{ item.name | default(omit) }}"
    deb: "{{ item.deb | default(omit) }}"
    state: present
    autoremove: "{{ apt_autoremove }}"
    force: "{{ apt_force }}"
    dpkg_options: "{{ apt_dpkg_options | default(omit) }}"
    install_recommends: "{{ apt_install_recommends }}"
    default_release: "{{ apt_default_release | default(omit) }}"
    update_cache: true
  loop: "{{ apt_packages }}"
  become: true
