---

- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: /etc/apt/apt.conf.d/99ansible
  ansible.builtin.template:
    src: etc/apt/apt.conf.d/99ansible.j2
    dest: /etc/apt/apt.conf.d/99ansible
    mode: 0444

- name: Configuration of APT change
  ansible.builtin.template:
    src: etc/apt/listchanges.conf.j2
    dest: /etc/apt/listchanges.conf
    mode: 0444
  when: aptconfig_listchanges_mail is not none

- name: Apply APT preferences
  ansible.builtin.template:
    src: "preferences.j2"
    dest: /etc/apt/preferences.d/preferences
    mode: 0644
  when: "apt_preferences | length > 0"

- name: Installing required packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{ _apt_required_packages }}"
  become: true

- name: Adding apt signing key
  ansible.builtin.apt_key:
    id: "{{ item.id | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    data: "{{ item.data | default(omit) }}"
    keyring: "{{ item.keyring | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
    state: present
  loop: "{{ apt_keys }}"
  become: true

- name: Adding repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ item.codename | default (omit) }}"
    update_cache: true
  loop: "{{ apt_repositories }}"
  when: item.repo is defined
  become: true

- name: Upgrading system
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade }}"
    update_cache: true
    autoremove: "{{ apt_autoremove }}"
  when: apt_upgrade
  become: true

- name: Installing packages
  ansible.builtin.apt:
    name: "{{ item.name | default(omit) }}"
    deb: "{{ item.deb | default(omit) }}"
    state: present
    autoremove: "{{ apt_autoremove }}"
    force: "{{ apt_force }}"
    dpkg_options: "{{ apt_dpkg_options | default(omit) }}"
    install_recommends: "{{ apt_install_recommends }}"
    default_release: "{{ apt_default_release | default(omit) }}"
    update_cache: true
  loop: "{{ apt_packages }}"
  become: true
