---
name: apt
properties:
  apt_autoremove:
    default: true
    required: false
    title: "apt_autoremove: Remove unused dependency packages"
    type: boolean
  apt_default_release:
    required: false
    title: "apt_default_release: Corresponds to the -t option for apt and sets pin priorities"
    type: string
  apt_dpkg_options:
    required: false
    title: "apt_dpkg_options: Add dpkg options to apt command (default: force-confdef,force-confold)"
    type: string
  apt_force:
    default: false
    required: false
    title: "apt_force: If yes, force installs/removes"
    type: boolean
  apt_install_recommends:
    default: false
    required: false
    title: "apt_install_recommends: Corresponds to the --no-install-recommends option for apt"
    type: boolean
  apt_keys:
    items:
      type: object
      properties:
        id:
          title: "id: The identifier of the key"
          type: string
          required: false
        file:
          title: "file: The path to a keyfile on the remote server to add to the keyring"
          type: string
          required: false
        data:
          title: "data: The keyfile contents to add to the keyring"
          type: string
          required: false
        keyring:
          title: "keyring: The path to specific keyring file in /etc/apt/trusted.gpg.d/"
          type: string
          required: false
        keyserver:
          title: "keyserver: The keyserver to retrieve key from"
          type: string
          required: false
        url:
          title: "url: The URL to retrieve key from"
          type: string
          required: false
        validate_certs:
          title: "validate_certs: If no, SSL certificates for the target url will not be validated"
          type: string
          required: false
    required: false
    title: apt_keys
    type: array
  apt_packages:
    items:
      type: object
      properties:
        name:
          title: "package_name: A package name, like foo, or package specifier with version, like foo=1.0."
          type: string
          required: false
        deb:
          title: "package_url: Path to a .deb package on the remote machine (url or local path)"
          type: string
          required: false
    required: false
    title: apt_packages
    type: array
  apt_repositories:
    items:
      type: object
      properties:
        repo:
          title: "repo: A source string for the repository"
          type: string
          required: false
        codename:
          title: "codename: Override the distribution codename to use for PPA repositories"
          type: string
          required: false
        update_cache:
          title: "update_cache: Run the equivalent of apt-get update when a change occurs"
          type: boolean
          required: false
          default: true
    required: false
    title: apt_repositories
    type: array
  apt_upgrade:
    default: no
    required: false
    title: "apt_upgrade: If yes, performs an aptittude upgrade, can be safe full or dist"
    type: string
type: object
