---
- name: ppa-package-install
  hosts: all
  become: true
  roles:
    - role: claranet.apt
  vars:
    apt_upgrade: true
    apt_packages:
      - name: nginx
      - name: "code=1.90.2-*"
      - name: java-11-amazon-corretto-jdk
    apt_repositories:
      - types: "deb"
        urls: "https://packages.microsoft.com/repos/vscode"
        suites: "stable"
        components: "main"
        key: https://packages.microsoft.com/keys/microsoft.asc
      - types: "deb"
        urls: "https://apt.corretto.aws"
        suites: "stable"
        components: "main"
        key: https://apt.corretto.aws/corretto.key
    apt_ppas:
      - repo: ppa:nginx/stable
        codename: trusty
