---
- name: ppa-package-install
  hosts: all
  become: true
  roles:
    - role: claranet.apt
  vars:
    apt_upgrade: true
    apt_packages:
      - name: nginx
      - name: nodejs
      - name: java-11-amazon-corretto-jdk
    apt_repositories:
      - types: "deb"
        urls: "https://deb.nodesource.com/node_18.x"
        suites: "{{ ansible_distribution_release|lower }}"
        components: "main"
        key: "{{ lookup('url', 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key', split_lines=False) }}"
      - types: "deb"
        urls: "https://apt.corretto.aws"
        suites: "stable"
        components: "main"
        key: https://apt.corretto.aws/corretto.key
    apt_ppas:
      - repo: ppa:nginx/stable
        codename: trusty
