---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
  - name: add group
    group:
      name: ansible
      state: present
  - name: add user
    user:
      name: ansible
      group: ansible
      home: /home/ansible

  - name: Add sudoers for ansible
    lineinfile:
      path: /etc/sudoers
      state: present
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
