---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
  - name: add group
    ansible.builtin.group:
      name: ansible
      state: present
  - name: add user
    ansible.builtin.user:
      name: ansible
      group: ansible
      home: /home/ansible

  - name: Add sudoers for ansible
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
