---
- name: basic-package-install
  hosts: all
  roles:
    - role: claranet.apt
      vars:
        apt_upgrade: true
        apt_packages:
          - name: apache2
          - name: "{{ ( ansible_distribution + '-' + ansible_distribution_release == 'Debian-bullseye' ) | ternary('python3-pip', 'python-pip') }}"
        repositories:
          - update_cache: true
