---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: ubuntu14
    image: ubuntu:14.04
  - name: ubuntu16
    image: ubuntu:16.04
  - name: ubuntu18
    image: ubuntu:18.04
  - name: debian9
    image: debian:9
  - name: debian10
    image: debian:10
  - name: debian11
    image: debian:11

provisioner:
  name: ansible
scenario:
  name: basic-package-install

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    verbose: true
    s: true

lint: |
  set -e
  yamllint .
  ansible-lint
