---
- name: basic-package-install
  hosts: all
  remote_user: ansible
  roles:
    - role: ansible-role-apt
  vars:
    apt_upgrade: true
    apt_packages:
      - name: apache2
      - name: python-pip
    repositories:
      - update_cache: true
