---
- name: spec-version-package-install
  hosts: all
  become: true
  roles:
    - role: claranet.apt
      vars:
        apt_upgrade: false
        apt_repositories:
          - types: deb
            urls: "http://ftp.debian.org/debian"
            suites: "{{ ansible_distribution_release | lower }}-backports"
            components: "main"
        apt_packages:
          - name: >-
              {%- if ansible_distribution == "Debian" and ansible_distribution_release == "stretch" -%}
                nginx=1.10.*
              {%- elif ansible_distribution == "Debian" and ansible_distribution_release == "buster" -%}
                nginx=1.14.*
              {%- elif ansible_distribution == "Debian" and ansible_distribution_release == "bullseye" -%}
                nginx=1.18.*
              {%- elif ansible_distribution == "Debian" and ansible_distribution_release == "bookworm" -%}
                nginx=1.22.*
              {%- else -%}
                nginx=1.18.*
              {%- endif -%}
