---
- name: spec-version-package-install
  hosts: all
  become: true
  roles:
    - role: claranet.apt
      vars:
        apt_upgrade: false
        apt_packages:
          - name: >-
              {%- if ansible_distribution == "Debian" and ansible_distribution_release == "bullseye" -%}
                nginx=1.18.*
              {%- elif ansible_distribution == "Debian" and ansible_distribution_release == "bookworm" -%}
                nginx=1.22.*
              {%- else -%}
                nginx=1.18.*
              {%- endif -%}
