---
- name: spec-version-package-install
  hosts: all
  remote_user: ansible
  roles:
    - role: claranet.apt
      vars:
        apt_upgrade: true
        apt_repositories:
          - repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
        apt_packages:
          - name: >-
              {%- if ansible_distribution == "Debian" and ansible_distribution_release == "stretch" -%}
                nginx=1.10.*
              {%- elif ansible_distribution == "Debian" and ansible_distribution_release == "buster" -%}
                nginx=1.14.*
              {%- elif ansible_distribution == "Debian" and ansible_distribution_release == "bullseye" -%}
                nginx=1.18.*
              {%- endif -%}
