---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: debian9
    image: debian:9
  - name: debian10
    image: debian:10
  - name: debian11
    image: debian:11
provisioner:
  name: ansible

scenario:
  name: spec-version-package-install
verifier:
  name: testinfra
  lint:
    name: flake8

lint: |
  set -e
  yamllint .
  ansible-lint
