---
- name: spec-version-package-install
  hosts: all
  remote_user: ansible
  roles:
    - role: ansible-role-apt
  vars:
    apt_upgrade: true
    apt_repositories:
      - repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
    apt_packages:
      - name: nginx=1.10.*
