---
- name: repo-package-install
  hosts: all
  remote_user: ansible
  roles:
    - role: claranet.apt
  vars:
    apt_upgrade: true
    apt_packages:
      - deb: "http://repo.zabbix.com/zabbix/6.1/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_6.1-2+{{ ansible_distribution |lower }}{{ ansible_distribution_version }}_all.deb"
      - name: zabbix-server-mysql
      - name: zabbix-frontend-php
