---
- name: repo-package-install
  hosts: all
  become: true

  roles:
    - role: claranet.apt
      vars:
        apt_upgrade: true
        apt_packages:
          - deb: "http://nginx.org/packages/{{ ansible_distribution | lower }}/pool/nginx/n/nginx/nginx_1.24.0-1~{{ ansible_distribution_release | lower }}_amd64.deb"
          - name: zabbix-server-mysql
          - name: zabbix-frontend-php
