---
- name: repo-package-install
  hosts: all
  remote_user: ansible
  roles:
    - role: ansible-role-apt
  vars:
    apt_upgrade: true
    apt_packages:
      - deb: http://repo.zabbix.com/zabbix/3.2/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_3.2-1+{{ ansible_distribution_release }}_all.deb
      - name: zabbix-server-mysql
      - name: zabbix-frontend-php
