---
name: Ansible Molecule

on:  # yamllint disable-line rule:truthy
  push:
    tags_ignore:
      - '*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.17
        with:
          command: lint

  setup:
    name: Setup scenarios matrix
    runs-on: ubuntu-20.04
    outputs:
      scenarios: ${{ steps.matrix.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v3
      - id: matrix
        run: |
          JSON="["

          for s in $(find molecule -mindepth 1 -maxdepth 1 -type d -exec basename "{}" \;); do
            JSON="${JSON}\"${s}\","
          done

          JSON="${JSON%?}"
          JSON="$JSON]"

          echo "::set-output name=scenarios::$(echo $JSON)"

  test:
    name: Scenario "${{ matrix.scenario }}" on ${{ matrix.config.image }}:${{ matrix.config.tag }}
    needs:
      - lint
      - setup
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(needs.setup.outputs.scenarios) }}
        config:
          - image: "amazonlinux"
            tag: "latest"
          - image: "fedora"
            tag: "28"
          - image: "debian"
            tag: "11"
          - image: "debian"
            tag: "10"
          - image: "ubuntu"
            tag: "20.04"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.17
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          scenario: ${{ matrix.scenario }}
